'use strict';
const store = require('./store');
const engine = require('./engine');
const { SEV } = require('./util');

const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const order = f => -SEV.indexOf(f.severity);
const pub = f => { const { chat, proposal, fps, ...r } = f; return r; };

function data(root) {
  const db = store.open(root), all = Object.values(db.findings).sort((a, b) => order(a) - order(b) || a.id.localeCompare(b.id));
  return { summary: engine.summary(root), findings: all.map(pub), scans: db.scans.map(({ items, ...s }) => s) };
}

function json(root) { return JSON.stringify(data(root), null, 2); }

function csv(root) {
  const cols = ['id', 'severity', 'status', 'category', 'kind', 'confidence', 'title', 'file', 'line', 'cwe', 'detectedBy', 'firstSeen', 'lastSeen'];
  const q = v => { v = Array.isArray(v) ? v.join('; ') : v ?? ''; v = String(v); if (/^[=+\-@]/.test(v)) v = "'" + v; return `"${v.replace(/"/g, '""')}"`; };   // neutralise CSV formula injection
  return [cols.join(','), ...data(root).findings.map(f => cols.map(c => q(f[c])).join(','))].join('\n');
}

function html(root) {
  const d = data(root), s = d.summary, c = s.counts;
  const card = f => `<div class="f ${f.severity}"><b>${esc(f.id)} · ${esc(f.severity.toUpperCase())}</b> ${esc(f.title)}<br><small>${esc(f.file)}${f.line ? ':' + f.line : ''} · ${esc(f.category)} · ${esc(f.status)} · confidence ${esc(f.confidence)} · ${esc((f.detectedBy || []).join(', '))}${f.cwe ? ' · ' + esc(f.cwe) : ''}</small>
    ${f.code ? `<pre>${esc(f.code)}</pre>` : ''}<p>${esc(f.description)}</p>${f.risk ? `<p><i>Risk:</i> ${esc(f.risk)}</p>` : ''}${f.fix ? `<p><i>Recommended:</i> ${esc(f.fix)}</p>` : ''}
    ${f.accept ? `<p><i>Accepted risk:</i> ${esc(f.accept.reason)} ${f.accept.expiry ? '(review ' + esc(f.accept.expiry) + ')' : ''}</p>` : ''}${f.fpNote ? `<p><i>False positive:</i> ${esc(f.fpNote)}</p>` : ''}</div>`;
  const by = st => d.findings.filter(f => st.includes(f.status));
  const sec = (t, l) => `<h2>${t} (${l.length})</h2>${l.map(card).join('') || '<p>None</p>'}`;
  const actions = [...new Set(by(store.ACTIVE).filter(f => f.fix).slice(0, 10).map(f => `<li><b>${esc(f.severity)}</b> ${esc(f.title)} — ${esc(f.fix)}</li>`))].join('');
  return `<!doctype html><meta charset=utf-8><title>Security Report — ${esc(s.project)}</title><style>
body{font:14px system-ui;max-width:900px;margin:30px auto;padding:24px 28px;color:#111;background:#f2f2f2;border-radius:18px}h1,h2{border-bottom:1px solid #E5E7EB;padding-bottom:4px}
.f{border-left:5px solid #888;padding:8px 12px;margin:10px 0;background:#fff;border-radius:10px;page-break-inside:avoid}.critical{border-color:#b00020}.high{border-color:#e65100}.medium{border-color:#f9a825}.low{border-color:#777}
pre{background:#eaeaea;padding:6px;overflow:auto}table{border-collapse:collapse}td,th{border:1px solid #ccc;padding:4px 10px}</style>
<div style="display:flex;align-items:center;gap:14px"><div><b style="font-size:18px">Security Center</b><br><small style="letter-spacing:.14em;text-transform:uppercase;color:#555;font-weight:600">Service Station Transformation</small></div></div>
<h1>Security Report — ${esc(s.project)}</h1>
<h2>Executive Summary</h2><p>Branch <b>${esc(s.branch)}</b> · last scan ${esc(s.lastScan || 'never')} · security score <b>${s.score}/100</b> (indicator only — review the findings). ${c.critical} critical, ${c.high} high open. ${s.accepted} accepted risk(s).</p>
<h2>Severity Summary</h2><table><tr>${SEV.slice().reverse().map(k => `<th>${k}</th>`).join('')}</tr><tr>${SEV.slice().reverse().map(k => `<td>${c[k]}</td>`).join('')}</tr></table>
${sec('Open Findings', by(store.ACTIVE))}${sec('Accepted Risks', by(['accepted_risk']))}${sec('Resolved Findings', by(['resolved']))}${sec('False Positives / Ignored', by(['false_positive', 'ignored']))}
<h2>Recommended Actions</h2><ol>${actions || '<li>No open findings with guidance.</li>'}</ol>
<p><small>Technical details: generated by Security Center. Print this page to save as PDF.</small></p><p style="text-align:center;color:#6e6e73"><small>© ${new Date().getFullYear()} Moazzam Saleem. All rights reserved.</small></p>`;
}

module.exports = { json, csv, html, data, pub };
